exports.USERS = [ // kam export const USERS
    {
        id:1,
        name: 'Valod',
        surname: 'Valodyan',
        email: 'Valod@mail.ru',
        gender:'male',
        password: "123",
        age: 25,
    },
    {
        id:2,
        name: 'Hakob',
        surname: 'Hakobyan',
        email: 'hakob@mail.ru',
        gender:'male',
        password: "123",
        age: 22,
    },
    {
        id:3,
        name: 'Tigran',
        surname: 'Tigranyan',
        email: 'tigran@mail.ru',
        gender:'male',
        password: "123",
        age: 35,
    },
    {
        id:4,
        name: 'Ben',
        surname: 'Benyan',
        email: 'ben@mail.ru',
        gender:'male',
        password: "123",
        age: 27,
    },
    {
        id:5,
        name: 'Gurgen',
        surname: 'Gurgenyan',
        email: 'gurgen@mail.ru',
        gender:'male',
        password: "123",
        age: 30,
    },
    {
        id:6,
        name: 'Vardan',
        surname: 'Vardanyan',
        email: 'vardan@mail.ru',
        gender:'male',
        password: "123",
        age: 20,
    },
    {
        id:7,
        name: 'Revik',
        surname: 'Keveyan',
        email: 'rev@mail.ru',
        gender:'male',
        password: "123",
        age: 22,
    },
    {
        id:8,
        name: 'Armine',
        surname: 'Grigoryan',
        email: 'armine@mail.ru',
        gender:'female',
        password: "123",
        age: 20,
    },
    {
        id:9,
        name: 'Jack',
        surname: 'Harlow',
        email: 'jack@mail.ru',
        gender:'male',
        password: "123",
        age: 22,
    },
    {
        id1:10,
        name: 'Tatev',
        surname: 'Sargsyan',
        email: 'tatev@mail.ru',
        gender:'female',
        password: "123",
        age: 25,
    }
];

exports.HOSTNAME = 'localhost';
exports.PORT = 3000;
